[versions]
detekt = "1.23.6"
kotlin = "2.0.0"
kotlinter = "4.4.0"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }

[libraries]
